- name: Workstation configuration
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

  roles:
    - packages
    - python-envs