- name: Workstation configuration via ansible pull
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - inventory/host_vars/{{ ansible_hostname}}.yml
  pre_tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

  roles:
    - packages
    - python-envs
