- name: Install common packages for all systems
  ansible.builtin.package:
    name: "{{ packages['all'] }}"
    state: present

- name: Install packages for each ansible group
  ansible.builtin.package:
    name: "{{ packages[item] }}"
    state: present
  loop: "{{ ansible_group }}"
  when: item in packages
