- name: Ensure python3 and python3-venv are installed
  apt:
    name:
      - python3
      - python3-venv
      - python3-pip
    state: present

- name: Ensure directory /home/{{ workstation_user }}/.py-envs exists
  file:
    path: "/home/{{ workstation_user }}/.py-envs"
    state: directory
    mode: "0755"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    recurse: yes

- name: Check if virtual environment exists
  stat:
    path: "/home/{{ workstation_user }}/.py-envs/{{ item.name }}/bin/activate"
  loop: "{{ python_envs }}"
  register: venv_paths

- name: Create python virtual environments
  command: python3 -m venv "/home/{{ workstation_user }}/.py-envs/{{ item.item.name }}"
  loop: "{{ venv_paths.results }}"
  when: not item.stat.exists

- name: Install packages in virtual environments
  become_user: "{{ workstation_user }}"
  pip:
    virtualenv: "/home/{{ workstation_user }}/.py-envs/{{ item.name }}"
    virtualenv_command: "python3 -m venv"
    name: "{{ item.packages }}"
    state: present
  loop: "{{ python_envs }}"
